version: '3.8'

services:
  fe:
    image: starrocks/fe-ubuntu:latest
    container_name: starrocks-fe
    ports:
      - "8030:8030"   # Web UI
      - "9030:9030"   # MySQL-compatible port
    environment:
      - JAVA_OPTS=-Duser.timezone=UTC
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8030"]
      interval: 10s
      timeout: 5s
      retries: 10

  be:
    image: starrocks/be-ubuntu:latest
    container_name: starrocks-be
    depends_on:
      fe:
        condition: service_healthy
    environment:
      - FE_SERVERS=127.0.0.1:9010
      - BE_ADDR=127.0.0.1:9050
